### ISSUE TITLE
Wildcard search

### ISSUE THREAD

**Issue by swilli6** [Alina-enni/lingdiggers#21]

**Comment by Alina-enni** [comment]
The wildcard search appears to be working. I simply made it visible by adding the output in the html document. To illustrate, here's what the query "fi" produces for the 5 Coldplay songs:

<img width="1508" alt="Screenshot 2022-02-17 at 14 05 12" src="https://user-images.githubusercontent.com/98087771/154478301-8fd52d02-53c2-45cc-a470-23c7b548b90c.png">
