### ISSUE TITLE
Test theme extraction

### ISSUE THREAD

**Issue by swilli6** [Alina-enni/lingdiggers#24]
Let's see if it's a useful feature for our project

**Comment by Alina-enni** [comment]
I was hoping to get started with this after I got the multi-word search and the wildcard search working pretty quickly. However, I am having trouble installing pke and the nltk resources it requires, so I don't know if I'll be able to work on this. I can't find a way to install the nltk stopwords, the universal tags, and the English language model on a Mac for some reason :/

**Comment by Alina-enni** [comment]
<img width="500" alt="Screenshot 2022-02-17 at 14 56 21" src="https://user-images.githubusercontent.com/98087771/154486223-2e66dfe4-517b-4661-a9fc-71543cec167b.png">

It behaves almost like the resources don't exist at all

**Comment by Alina-enni** [comment]
Oh boy it took a lot of wrangling and desperation, but I managed to get it working! I found a solution for installing the resources form nltk and spacy. I used the current version of lyrics2.txt in our repo as a document to extract themes from and this is the output:

<img width="457" alt="Screenshot 2022-02-17 at 15 24 59" src="https://user-images.githubusercontent.com/98087771/154491012-c4091b03-8ba6-433a-9883-8a3cb70f123e.png">

I have no idea what 'cornflake girl lyrics' refers to xD

**Comment by miglamigla** [comment]
Apparently, a song by Tori Amos :D I wonder, what the sah is
Anyhow, that looks really interesting - especially if we had even more songs in the data file.
Maybe we could show these themes on the initial search page (before searching for anything)?

**Comment by Alina-enni** [comment]
Yeah I think that is a good idea! Let's test out the theme extraction for a larger index and see if the results seem at all useful or sensible.
