### ISSUE TITLE
HTML page created

### ISSUE THREAD

**Issue by Alina-enni** [Alina-enni/lingdiggers#6]
I've create a HTML document called _htmlpage.html_. I used some CSS too to help the formatting along but feel free to make any changes you want to any of the code. 

I would advise against using tables for layouts though as that is kind of an outdated method and there are way more efficient methods (like Bootstrap) out there for arranging elements on a page :)

**Comment by swilli6** [comment]
I have added some HTML content to the file. I will open another issue and flag @miglamigla!
