### ISSUE TITLE
Search engine

### ISSUE THREAD

**Issue by Alina-enni** [Alina-enni/lingdiggers#9]
1. The queries should not be hard-coded. Instead your program should ask the user to type the query. Make this run in a loop, so that the user can run as many queries they like. Also come up with some user input that tells the program to quit, such as an empty string or a specific keyword.

**Comment by miglamigla** [comment]
Added an IF loop within the WHILE loop. Seems to work for me and also to close the app with Enter. 
Please check if it works for you too

**Comment by Alina-enni** [comment]
It works, so I will close this issue
